#!/bin/sh
set -eu

case "$1" in
show)
  printf '[{"labels":['
  separator=
  while IFS= read -r label; do
    printf '%s"%s"' "$separator" "$label"
    separator=,
  done < "$CANARY_STATE"
  printf ']}]\n'
  ;;
update)
  next_state="${CANARY_STATE}.next"
  : > "$next_state"
  shift 2
  for arg in "$@"; do
    case "$arg" in
    --set-labels=*)
      label=${arg#--set-labels=}
      if [ -n "$label" ]; then
        printf '%s\n' "$label" >> "$next_state"
      fi
      ;;
    esac
  done
  mv "$next_state" "$CANARY_STATE"
  ;;
*)
  printf 'unsupported fake bd command\n' >&2
  exit 1
  ;;
esac
